### ISSUE TITLE
AD Blocker Doesn't Block with MacOS Packaged App

### ISSUE THREAD

**Issue by talmax1124** [youp-han/Electron-YTDeskTopWithAdBlocker#1]

**Comment by youp-han** [comment]
Sorry for the late response.. 
I used the Adblocker and packaged my app and it works great on windows, and on steamOS.
I used the 1.26.6 version before, and now I use 1.27.1.. The version increased 'coz the older version didn't block 
Ads in Youtube, but the latest version works again.
